# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/YuchenHui22314"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "Google Scholar"
name = "Google Scholar"
url = "https://scholar.google.ca/citations?user=_fiTdwUAAAAJ&hl=en"

[social.params]
icon = "brand-twitter"
