# Configure main menu and social menu

# [[main]]
# identifier = "home"
# name = "Home"
# url = "/"
# [main.params]
# icon = "home"
# newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/YuchenHui22314"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/yuchen_xier"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "Google Scholar"
name = "Google Scholar"
url = "https://scholar.google.ca/citations?user=_fiTdwUAAAAJ&hl=en"

[social.params]
icon = "Google_Scholar_logo"

[[social]]
identifier = "email_address"
name = "email_address"
url = "mailto:yuchen.hui@umontreal.ca"

[social.params]
icon = "mail_icon"    

[[social]]
identifier = "linkedin"
name = "linkedin"
url = "https://www.linkedin.com/in/yuchen-hui-179303251/"

[social.params]
icon = "linkedin"    
